# Generated by Django 3.1.4 on 2020-12-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenantsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='lattitude',
            field=models.DecimalField(decimal_places=15, max_digits=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='logitude',
            field=models.DecimalField(decimal_places=15, max_digits=100),
        ),
    ]
